### ISSUE TITLE
Use JWT

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peerpad#1]
It would be interesting to use JWT instead of <insert custom format> to share the keys. To continue sharing these keys through the url, we just need to serialize it and encode it.

Since JWT is valid JSON, we can transfer it as a `dag-cbor` node and then use the CID to base64 encode it ⚡️

**Comment by diasdavid** [comment]
@pgte thoughts here?

**Comment by pgte** [comment]
I'm not sure I understand how JWT fits here. As I understand it and used it in the past, JWT is a way to transfer and verify claims based in a signature.

To give you some background, currently peerpad uses an asymmetric key. Readers have access to the public key, and readers have access to the private key. Both use the public key to validate the signature of messages from other peers. Also, a symmetric key is deterministically derived from the public key, which serves to encrypt and decrypt the text in IPFS.

@diasdavid Could you elaborate on how you see JWT fit here (or any change to the way peerpad works currently)? :)

**Comment by diasdavid** [comment]
You are right, I was thinking that a JWT token also transferred the PublicKey and so, it would be a good format for us to transfer the PublicKeys too. nvm then :)
