### ISSUE TITLE
CRDT protocol over IPFS

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad#107]
Currently, the CRDT protocol being used is the native Y.js protocol, which is independent of IPFS. Each message is signed and encrypted, and then sent over the IPFS pubsub network for all participating nodes. In addition to that, individual p2p messages (Y.js requires individual p2p messages for bootstrapping) are channeled over libp2p connection using a specific protocol handler.

(The snapshot funcionality is independent of Y.js and uses the IPFS file API.)

Optimally, instead of using the Y.js CRDT protocol, we should put these changes into IPFS and make nodes follow / participate using a pubsub propagation mechanism (perhaps IPNS, if it's a good fit for multiple writers).

Some work towards this has already been accomplished by @haadcode's [ipfs-log](https://github.com/haadcode/ipfs-log#readme) and [tevere](https://github.com/ipfs-shipyard/tevere).

This issue aims to research and define the best way to implement a generic (Y.js-like) CRDT over IPFS that is more native and does not have the need to have a specific protocol handler.

**Comment by diasdavid** [comment]
@pgte please use https://github.com/ipfs/research-crdt for this discussion :)
