### ISSUE TITLE
upgrade to IPFS v0.27

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad#125]
Have been testing PeerPad with js-ipfs v0.27.

The libp2p-websocket-star transport is looking very promising! 🌟

Test results are looking good under normal connected scenarios, but things tend to break when testing disconnection and subsequent reconnection.

Right now, upgrading to js-ipfs v0.27 depends on these fixes:

- [x] https://github.com/libp2p/js-libp2p-websocket-star/pull/39
- [x] https://github.com/libp2p/js-libp2p-floodsub/pull/52

**Comment by diasdavid** [comment]
https://github.com/libp2p/js-libp2p-websocket-star/pull/39 was merged and released as a patch version.

peerpad should be working well js-ipfs 0.27 and webrtc-star, right? I trust you tested it a couple of times before the release was done.

**Comment by pgte** [comment]
I tested discovery, pubsub and the files API, but I think I missed testing reconnection, and version 0.27.0 has a regression there when using websocket-star— I believe that’s what these latest fixes fix..

**Comment by pgte** [comment]
@diasdavid BTW, I know I'm conflating js-ipfs v0.27 and using websocket-star, but I want to take this opportunity to make websocket-star viable to improve app stability. :)

**Comment by diasdavid** [comment]
@pgte ack :) that is what I was missing and finding strange.

Good news, just deployed the latest websocket-star-rendezvous, you should be able to test this again and get positive results in all the tests :) 

```
=====> Application deployed:
       https://ws-star.discovery.libp2p.io
```

**Comment by pgte** [comment]
Awesome, looking good, can't reproduce data loss with IPFS and linked dependencies master branches. Thanks @diasdavid !

**Comment by diasdavid** [comment]
Great to hear! @pgte try a fresh install, the fixes were released as patches, no linking should be necessary.

**Comment by pgte** [comment]
Done via peerpad-core@0.10.0 - https://github.com/ipfs-shipyard/peerpad-core/pull/6
