### ISSUE TITLE
Domain: peerpad.net vs. peerpad.io

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/peerpad#17]
I registered both a while ago. The dotIO TLD has a really crappy track record of how they operate their DNS servers, so I'd be happy to not add more .io domains: https://hn.algolia.com/?query=io%20dns&sort=byDate&dateRange=all&type=story&prefix&page=0

I'd propose going with peerpad.net.

**Comment by diasdavid** [comment]
peerpad.net it is, let's get it ready to be deployed https://github.com/ipfs-shipyard/peerpad/issues/46 :)
