### ISSUE TITLE
snapshot scheme

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad#20]
Viewer is an external dependency, is a bundled JS in IPFS.
A snapshot is an IPFS UnixFS directory containing 2 files:

* `index.html`
* `meta.json`

`index.html` contains a script src to the viewer, served through IPFS gateway.
`meta.json` contains the following information:

```js
{
  "encryptedTitle": "base64 string containing the encrypted title of the document",
  "encryptedDocument": "base64String containing the encrypted body of the document",
  "viewerVersion": "0.2"
}
```

**Comment by pgte** [comment]
Done in branch 0.2

**Comment by diasdavid** [comment]
🎉🎉
