### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peerpad#25]
I feel that docs are really important for this project and instead ARCHITECTURE.md and SECURITY.md should be available at the root repo and linked from the README too.

README.md should have a bold disclaimer that Peerpad hasn't been audited yet (add the open lock 🔓) and SECURITY.md should have that disclaimer as well.

**Comment by pgte** [comment]
README already contains links to them.

Fixed via e54f6b4
