### ISSUE TITLE
encrypt data at rest

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad#4]
Out of the box, Y.js uses the local store to store the CRDT, which means that records that contain parts of the content are stored unencrypted.

We should encrypt data at rest using a symmetric key derived from the "read key".

**Comment by pgte** [comment]
Done in v0.2 by creating and using [y-indexeddb-encrypted](https://www.npmjs.com/package/y-indexeddb-encrypted).

**Comment by diasdavid** [comment]
🎉🎉🎉🎉
