### ISSUE TITLE
homepage should have separate smaller bundle

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad#52]
For faster loading, the homepage JS bundle should not include all the app dependencies.

In order to shake big dependencies like js-ipfs, it would mean directly importing key and name-generating dependencies in core (something like `require('peerpad-core/src/backend/keys/generate')`, etc.).

Also, dynamic loading on the app would require having something like a "loading" screen while loading JS, before the app is fully funcional.

**Comment by olizilla** [comment]
smaller bundles; We have them!

Fixed in #72
