### ISSUE TITLE
Disable non implemented UI elements

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peerpad#55]
Such as:

![image](https://user-images.githubusercontent.com/1211152/31999830-953516fe-b98c-11e7-8b0d-27cf6785e5d9.png)

and 
![image](https://user-images.githubusercontent.com/1211152/31999843-a1161f86-b98c-11e7-8540-d7eebd71d2c7.png)

**Comment by olizilla** [comment]
@diasdavid what's the expected behaviour of the `+` button? Should it redirect you to a new tab with a pad with a new random name, like the start button on the homepage?

**Comment by olizilla** [comment]
and if so, new tab or current tab?

**Comment by diasdavid** [comment]
@olizilla the + button would be to invite other users but that won't be present until we have some kind of auth.
