### ISSUE TITLE
Shapshots should contain date 

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peerpad#56]
![image](https://user-images.githubusercontent.com/1211152/31999875-b835ddc8-b98c-11e7-8664-9da6a0efca2a.png)

Also, please make the box bigger so that we can see the whole hash

**Comment by olizilla** [comment]
@diasdavid @pgte the list of snapshots for a doc are lost when the user refreshes the page, and we don't currently have timestamp info on the objects. Do you want the UI to add them to localstorage / or is it a peerpad-core responsibility?

**Comment by pgte** [comment]
Right now peerpad-core only takes the snapshot, so it's up to the app to do whatever with it.
(Later on we plan to store docs and have a directory view, but right now that's still a bit fuzzy.. (at least for me)).

**Comment by pgte** [comment]
@olizilla while you're at it, could you please make the hash link open in a new window?

**Comment by olizilla** [comment]
👍 

note to self: fix #54 while we're in here.

**Comment by olizilla** [comment]
@pgte It is ok to store the snapshot hash and key in localStorage? I know this is an alpha with no security promises, but I still wanted to check.

**Comment by pgte** [comment]
Yes, since each snapshot has it's own independent decryption key. Access to these doesn't compromise the "future" of the document.

**Comment by olizilla** [comment]
@pgte last question! Snapshots need to be keyed on current document, so I know which ones to load when we render a new pad. Is it sensible to use the readKey for the current doc, since the name is mutable.

**Comment by pgte** [comment]
The document name should not change, you're probably thinking about the document title, so it's safe.

In regards to the document title changing, let's track this on another issue, I've neglected this part.

**Comment by olizilla** [comment]
Ah, I think name and title are currently conflated in the UI. `name` is plucked from the the url, set as state, and then mutated when the user edits the title. I'll pull them apart.
