### ISSUE TITLE
Blank when opening from IPFS hash 

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peerpad#67]
See https://ipfs.io/ipfs/QmYqBG2aizE4cgrPSUwYHw2vL35F2GPLGpmdzgmnBZQEqH/

**Comment by diasdavid** [comment]
It actually seems that `npm run build` is just not generating the app properly.

**Comment by olizilla** [comment]
Looks like some templates aren't being interpolated 
```
favicon.ico:1 GET https://ipfs.io/ipfs/QmYqBG2aizE4cgrPSUwYHw2vL35F2GPLGpmdzgmnBZQEqH/%PUBLIC_URL%/favicon.ico 400 (Bad Request)
```

`/%PUBLIC_URL%` should probably be `public`

**Comment by olizilla** [comment]
build process needs env vars it seems

https://github.com/ipfs-shipyard/peerpad/blob/1301536ed309576d5ae733f5dbf1ee3ef0fa4a14/config/paths.js#L28-L33

I'll look into it.

**Comment by olizilla** [comment]
```sh
PUBLIC_URL="./" npm run build
``` 
might work. I'm tying it now. I'll need to sweep through the app and fix absolute paths (as per usual, whoop whoop)

**Comment by olizilla** [comment]
To clarify, that might work for now as a quick fix, as the app is using the hash router, so the real path never changes... my preferred fix would be to pull out all the create-react-app-ejected noise and just wire up enough browserify to do what we need. I don't know how long that'll take, so I'd rather get what we have working first.

**Comment by olizilla** [comment]
All good now @diasdavid 

https://ipfs.io/ipfs/QmZwkjxYCW6ud2akqzfoJe2q264dPbqubFVcGo4bauaG3c/#/w/markdown/6oPYZxZnLmTKjWUoGZ8GcC/4XTTMB1BFgUgr3YJTHotVe32MNHBvKnLmqU9K8Mot5cVPAwGm/K3TgUfr3uWhKWJwPEjgLQDJR6DdZriabzr2QJhk5Cg9TsddxvsZuVaGsrqk6v6CwZhWteCrdz6eCYFYj4mWa459krXT2pZJoNxQA7bygkpHZpJQtwV7HiuvXtmsf6vM3zosVv75j
