### ISSUE TITLE
Failed insecure connection to ws://star-signal.cloud.ipfs.team

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/peerpad#73]
I can't see why peerpad / ipfs-js is trying to to use the `ws://` protocol to connect to `star-signal.cloud.ipfs.team` but in the browser console from 

https://ipfs.io/ipfs/QmYD5hksXbSRRY4C3fFsneBuCqfcU8JS64wfLum896jFBc/#/w/markdown/7F6ctJK5wpcKhKNAbNMpH1/4XTTM4hvH1yP5sLm7gD1VkM2ovu9tey6AegEXS43KHSkKzGCd/K3TgUWpx1DQFJJnM3bUPf8urqqEV7SdXS6QdgWGCeAmyDb9v6NM3GZvzcWJ4uPqAbK26KZrpqEHfZFuvibU9HFmmMeZjJf71AmP21ZUZ9hV26KAtgJxnoQ4Z5BkFeMPJt17w4EzH

I can see:

```
Mixed Content: The page at 'https://ipfs.io/ipfs/QmYD5hksXbSRRY4C3fFsneBuCqfcU8JS64wfLum896jFBc/#/w/markdown/7F6ctJK5wpcKhKNAbNMpH1/4XTTM4hvH1yP5sLm7gD1VkM2ovu9tey6AegEXS43KHSkKzGCd/K3TgUWpx1DQFJJnM3bUPf8urqqEV7SdXS6QdgWGCeAmyDb9v6NM3GZvzcWJ4uPqAbK26KZrpqEHfZFuvibU9HFmmMeZjJf71AmP21ZUZ9hV26KAtgJxnoQ4Z5BkFeMPJt17w4EzH' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://star-signal.cloud.ipfs.team/socket.io/?EIO=3&transport=websocket'. This request has been blocked; this endpoint must be available over WSS.
```

The initial page request is over https... and i can see the multiaddress in ipfs-js over here suggests wss...

https://github.com/ipfs/js-ipfs/blob/1e5dd2c091a101d1c9d6e6d66e6e527e662a79b8/src/core/runtime/config-browser.json#L4

@diasdavid @pgte can you help?

**Comment by pgte** [comment]
Is this the uglified production build? If so, this is because IPFS can’t be uglified.
I’ve been playing with this and I think we’ll have to drop Uglification for the time being..

**Comment by olizilla** [comment]
i haven't dug into the build process yet, but I can see `uglifyjs-webpack-plugin` in the `package.json` so I assume so.

> ipfs can't be uglified

oh my. isn't it most of the bundle size? unminified, the main bundle it's about 1.4Mb, which isn't ideal, but as apple.com is > 5Mbs today, I think we'll be fine running unminified for now.

**Comment by olizilla** [comment]
the webpack plugin seems to already be disabled in prod
https://github.com/ipfs-shipyard/peerpad/blob/1301536ed309576d5ae733f5dbf1ee3ef0fa4a14/config/webpack.config.prod.js#L267

The issue feels a bit more like the ipfs node needs to be configured to use wss rather than trying ws but I'm not familiar enough that plumbing. https://github.com/ipfs/js-ipfs/blob/1e5dd2c091a101d1c9d6e6d66e6e527e662a79b8/src/core/runtime/config-browser.json#L4

**Comment by pgte** [comment]
We were using a different Uglification plugin, not exactly sure of why. Have PR to remove it here: https://github.com/ipfs-shipyard/peerpad/pull/74
