### ISSUE TITLE
Request: more appropriate icons

### ISSUE THREAD

**Issue by nicola** [ipfs-shipyard/peerpad#82]
<img width="55" alt="screen shot 2017-10-29 at 11 56 43 am" src="https://user-images.githubusercontent.com/1424850/32143383-51ad101e-bca0-11e7-93fd-c34eab442017.png">

The two icons make me think about adding a picture or adding a link, rather than taking a snapshot, can I request better icons?

**Comment by akrych** [comment]
I prepare few new icons:)
[icons.zip](https://github.com/ipfs-shipyard/peerpad/files/1426989/icons.zip)

**Comment by nicola** [comment]
You folks are so great and fast
