### ISSUE TITLE
Missing important links

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/peerpad#89]
It needs:
- Link to SECURITY.md (really important) (top and bottom)
- Link to ARCHITECTURE.md (top and bottom)
- Link to this repo on Github (top and bottom)
- Link to js-ipfs from the word IPFS on the welcome page
- Link to http://y-js.org/ from the word CRDT on the welcome

See docs on https://github.com/ipfs-shipyard/peerpad/tree/master/docs

**Comment by diasdavid** [comment]
Still missing Security at the top 
![image](https://user-images.githubusercontent.com/1211152/32146095-6e178372-bcca-11e7-8de8-995e1ab533c5.png)

![image](https://user-images.githubusercontent.com/1211152/32146102-88bc3af6-bcca-11e7-9a6e-f9a0a7c87e28.png)

**Comment by diasdavid** [comment]
Also missing link to the Githubs

**Comment by pgte** [comment]
@diasdavid the links are embedded in the homepage itself (for instance the Github link is in the "Peerpad is __open-source__" word) , but I'll add them to the footer / header.

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/32369323-ac2cbce0-c080-11e7-8b1d-dab7de7eac30.png)

replace "Github repo" by "Open Source"
