### ISSUE TITLE
generated index.html for snapshots is giant

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/peerpad#99]
The generated index.html pages are not minified, and they are very large. We should probably try to ship the smallest thing possible for this.

**Comment by whyrusleeping** [comment]
The one i'm looking at appears to be around 1.5MB

**Comment by pgte** [comment]
Right now, the build process reports that the file sizes after gzip are:

```
File sizes after gzip:

  782.92 KB (+85 B)  build/static/js/0.e8155902.chunk.js
  624.03 KB          build/static/js/main.bundle.js
  329.63 KB          build/static/js/viewer.bundle.js
  152.05 KB          build/static/js/1.056483da.chunk.js
  151.9 KB           build/static/js/2.6c6a3cc3.chunk.js
  22.49 KB           build/static/css/main.31a17017.css
```

The `viewer.bundle.js` (329.63 KB) is the one loaded into snapshots, but still is quite large IMO.

**Comment by pgte** [comment]
Current bundle sizes:

```
File sizes after gzip:

  442.82 KB  build/static/js/0.fd47217c.chunk.js
  371.91 KB  build/static/js/main.bundle.js
  149.13 KB  build/static/js/viewer.bundle.js
  104.57 KB  build/static/js/1.056483da.chunk.js
  104.46 KB  build/static/js/2.6c6a3cc3.chunk.js
  22.49 KB   build/static/css/main.31a17017.css
```

viewer is 149 KB zipped, 498 KB unzipped.

**Comment by whyrusleeping** [comment]
That's better, can always make things smaller, but a 3x improvement is
great!

**Comment by whyrusleeping** [comment]
It might be nice if the encrypted content was stored separately from the viewer, so the generated directory could then look like:
```
/
  index.html
  encrypted-pad
```

That way the index could be cached, and always know to load a relative path of `./encrypted-pad`
